name: exomdn2
channels:
    - conda-forge
dependencies:
    - python=3.10.*
    - tensorflow=2.*
    - tensorflow-probability=0.15.*
    - scikit-learn=1.1.1
    - numpy
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - joblib
    - ipywidgets
    - jupyter
    - pip
